### ISSUE TITLE
Audio Syncing Issues For Dubbed Titles

### ISSUE THREAD

**Issue by IkeThermite** [thrkll/ruv-dl#13] opened 2024-10-14 17:56 UTC
When downloading titles that have been dubbed into Icelandic the audio is often out of sync.

To reproduce: Download Blæja II - Mömmuskóli and play in VLC. 
For this episode, I believe the correct delay is about 1.5 seconds, and seems to be due to the additional title card. However, other episodes in this same season have different audio desyncs, and some of them are fine.

(I am trying to download dubbed titles so I can add English subtitles and practice my Icelandic. I know ord.ruv exists but it doesn't have great cartoons like Bluey.)

**Comment by thrkll** [comment] 2024-10-14 23:36
Good catch! Thanks for raising the issue @IkeThermite. 

The cause of the problem seems to be that `ruv-dl` was not properly handling audio streams based on the given resolution. Specifically, when downloading HLS content, ffmpeg didn't explicitly map the corresponding audio/video streams, which led to de-synchronization. Interestingly, there seems to be some time-relevant differences in the audio streams from RÚV that cause the de-synchronization.

This is now fixed with the latest release. Mapping the streams has some consequences for non-HLS content (i.e. radio shows that are audio only) so that was accounted for. 

Good luck with the Icelandic studies and please reach out if you find some more out-of-sync content with the latest release.

**Closed as completed** 2024-10-14 23:36 UTC
Labels: bug

**Comment by IkeThermite** [comment] 2024-10-15 20:01
Can confirm that this works now. Thank you very much for the great code and quick fix.
